version: "3.9"

networks:
  local:
    name: testament_daml

services:
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    shm_size: 256mb
    volumes:
      - ./network/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - local

  domain:
    image: digitalasset/canton-open-source:2.3.3
    ports:
      - "5000:5000"
      - "5001:5001"
    command: daemon -c /configs/domain.conf
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=domain
      - POSTGRES_DB=domain
      - POSTGRES_PASSWORD=domain
    volumes:
      - ./network/configs:/configs
    networks:
      - local
    depends_on:
      - postgres

  contract-builder:
    image: digitalasset/daml-sdk:2.3.2
    user: root
    command: /scripts/build.sh
    environment:
      - WORKDIR=/home/daml/contracts
    volumes:
      - ./contracts:/home/daml/contracts
      - ./network/scripts:/scripts

  ledger.gov:
    image: digitalasset/canton-open-source:2.3.3
    ports:
      - "6000:6000"
      - "6001:6001"
    entrypoint: /scripts/start-ledger.sh
    environment:
      - PARTICIPANT_NAME=government
      - PARTICIPANT_USER=govadmin
      - JWKS_URL=http://auth.gov:8080/jwks
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=government
      - POSTGRES_DB=government
      - POSTGRES_PASSWORD=government
    volumes:
      - ./network/configs:/configs
      - ./network/scripts:/scripts
      - ./contracts/:/contracts
    networks:
      - local
    depends_on:
      - domain
      - contract-builder

  json.gov:
    build: 
      context: ./network
      dockerfile: Dockerfile.json
    image: daml/json-api
    ports:
      - "7575:7575"
    environment:
      - LEDGER_HOST=ledger.gov
      - LEDGER_PORT=6000
    volumes:
      - ./network/configs:/configs
    networks:
      - local
    depends_on:
      - ledger.gov

  auth.gov:
    build: 
      context: ./auth-server
    image: daml/auth-server
    ports:
      - "8080:8080"
    environment:
      - PARTICIPANT_USER=govadmin
      - PARTICIPANT_PASSWORD=govadminpassword
    networks:
      - local

  # TODO: setup nginx.gov

  ledger.provider:
    image: digitalasset/canton-open-source:2.3.3
    ports:
      - "6002:6000"
      - "6003:6001"
    entrypoint: /scripts/start-ledger.sh
    environment:
      - PARTICIPANT_NAME=provider
      - PARTICIPANT_USER=provider
      - JWKS_URL=http://auth.provider:8080/jwks
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=provider
      - POSTGRES_DB=provider
      - POSTGRES_PASSWORD=provider
    volumes:
      - ./network/configs:/configs
      - ./network/scripts:/scripts
      - ./contracts/:/contracts
    networks:
      - local
    depends_on:
      - domain
      - contract-builder

  json.provider:
    build: 
      context: ./network
      dockerfile: Dockerfile.json
    image: daml/json-api
    ports:
      - "7576:7575"
    environment:
      - LEDGER_HOST=ledger.provider
      - LEDGER_PORT=6000
    volumes:
      - ./network/configs:/configs
    networks:
      - local
    depends_on:
      - ledger.provider

  auth.provider:
    build: 
      context: ./auth-server
    image: daml/auth-server
    ports:
      - "8081:8080"
    environment:
      - PARTICIPANT_USER=provider
      - PARTICIPANT_PASSWORD=providerpassword
    networks:
      - local

  # TODO: start provider gateway

  # TODO: add bank nodes

  # TODO: start bank gateway

  # TODO: initialize testament factory
